name: Test

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - develop
      - release/**

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt pytest
      - run: pytest tests/ -v